import { StyleSheet } from '@react-pdf/renderer';

const COLOR_TEXTO = '#173f35';
const COLOR_SECUNDARIO = '#66756f';
const COLOR_BORDE = '#dce7e2';
const COLOR_FONDO = '#f5f8f6';

export function crearEstilosPdf(colorMarca: string) {
  return StyleSheet.create({
    page: {
      backgroundColor: '#ffffff',
      color: COLOR_TEXTO,
      fontFamily: 'Helvetica',
      fontSize: 9,
      lineHeight: 1.35,
      paddingBottom: 52,
      paddingHorizontal: 38,
      paddingTop: 34,
    },
    brandRule: {
      backgroundColor: colorMarca,
      height: 4,
      left: 0,
      position: 'absolute',
      right: 0,
      top: 0,
    },
    header: {
      alignItems: 'center',
      borderBottomColor: COLOR_BORDE,
      borderBottomWidth: 1,
      flexDirection: 'row',
      justifyContent: 'space-between',
      marginBottom: 22,
      paddingBottom: 14,
    },
    brand: {
      alignItems: 'center',
      flexDirection: 'row',
      maxWidth: '72%',
    },
    logo: {
      height: 42,
      marginRight: 11,
      objectFit: 'contain',
      width: 42,
    },
    logoFallback: {
      alignItems: 'center',
      backgroundColor: colorMarca,
      borderRadius: 6,
      height: 42,
      justifyContent: 'center',
      marginRight: 11,
      width: 42,
    },
    logoInitial: {
      color: '#ffffff',
      fontFamily: 'Helvetica-Bold',
      fontSize: 18,
    },
    brandName: {
      color: COLOR_TEXTO,
      fontFamily: 'Helvetica-Bold',
      fontSize: 16,
      marginBottom: 2,
    },
    professional: {
      color: COLOR_SECUNDARIO,
      fontSize: 8,
    },
    documentMeta: {
      color: COLOR_SECUNDARIO,
      fontSize: 8,
      textAlign: 'right',
    },
    documentTitle: {
      color: colorMarca,
      fontFamily: 'Helvetica-Bold',
      fontSize: 9,
      marginBottom: 2,
      textTransform: 'uppercase',
    },
    continuationHeader: {
      alignItems: 'center',
      borderBottomColor: COLOR_BORDE,
      borderBottomWidth: 1,
      flexDirection: 'row',
      justifyContent: 'space-between',
      marginBottom: 18,
      paddingBottom: 9,
    },
    continuationBrand: {
      color: COLOR_TEXTO,
      fontFamily: 'Helvetica-Bold',
      fontSize: 10,
    },
    continuationPatient: {
      color: COLOR_SECUNDARIO,
      fontSize: 8,
      textAlign: 'right',
    },
    patientEyebrow: {
      color: colorMarca,
      fontFamily: 'Helvetica-Bold',
      fontSize: 8,
      letterSpacing: 0.8,
      marginBottom: 5,
      textTransform: 'uppercase',
    },
    patientName: {
      color: COLOR_TEXTO,
      fontFamily: 'Helvetica-Bold',
      fontSize: 20,
      lineHeight: 1.18,
      marginBottom: 18,
    },
    macroRow: {
      flexDirection: 'row',
      gap: 7,
      marginBottom: 22,
    },
    macroCard: {
      backgroundColor: COLOR_FONDO,
      borderColor: COLOR_BORDE,
      borderRadius: 6,
      borderWidth: 1,
      flexGrow: 1,
      paddingHorizontal: 10,
      paddingVertical: 9,
    },
    macroValue: {
      color: colorMarca,
      fontFamily: 'Helvetica-Bold',
      fontSize: 13,
      marginBottom: 1,
    },
    macroLabel: {
      color: COLOR_SECUNDARIO,
      fontSize: 7,
      textTransform: 'uppercase',
    },
    sectionTitle: {
      color: COLOR_TEXTO,
      fontFamily: 'Helvetica-Bold',
      fontSize: 12,
      marginBottom: 9,
    },
    meal: {
      borderColor: COLOR_BORDE,
      borderRadius: 7,
      borderWidth: 1,
      marginBottom: 11,
      overflow: 'hidden',
    },
    mealHeader: {
      alignItems: 'center',
      backgroundColor: COLOR_FONDO,
      borderLeftColor: colorMarca,
      borderLeftWidth: 4,
      flexDirection: 'row',
      justifyContent: 'space-between',
      paddingHorizontal: 11,
      paddingVertical: 8,
    },
    mealName: {
      color: COLOR_TEXTO,
      fontFamily: 'Helvetica-Bold',
      fontSize: 10,
    },
    mealTime: {
      color: colorMarca,
      fontFamily: 'Helvetica-Bold',
      fontSize: 8,
    },
    mealDescription: {
      color: COLOR_SECUNDARIO,
      fontSize: 8,
      paddingHorizontal: 11,
      paddingTop: 7,
    },
    itemHeader: {
      borderBottomColor: COLOR_BORDE,
      borderBottomWidth: 1,
      color: COLOR_SECUNDARIO,
      flexDirection: 'row',
      fontSize: 6.5,
      marginHorizontal: 11,
      paddingBottom: 4,
      paddingTop: 7,
      textTransform: 'uppercase',
    },
    itemRow: {
      borderBottomColor: '#edf2ef',
      borderBottomWidth: 1,
      flexDirection: 'row',
      marginHorizontal: 11,
      paddingVertical: 6,
    },
    itemLast: {
      borderBottomWidth: 0,
    },
    itemMain: {
      paddingRight: 8,
      width: '54%',
    },
    itemName: {
      color: COLOR_TEXTO,
      fontFamily: 'Helvetica-Bold',
      fontSize: 8.5,
      marginBottom: 1,
    },
    itemPortion: {
      color: COLOR_SECUNDARIO,
      fontSize: 7,
    },
    itemKcal: {
      color: COLOR_TEXTO,
      fontFamily: 'Helvetica-Bold',
      textAlign: 'right',
      width: '13%',
    },
    itemMacros: {
      color: COLOR_SECUNDARIO,
      textAlign: 'right',
      width: '33%',
    },
    emptyMeal: {
      color: COLOR_SECUNDARIO,
      fontStyle: 'italic',
      paddingHorizontal: 11,
      paddingVertical: 9,
    },
    note: {
      backgroundColor: COLOR_FONDO,
      borderColor: COLOR_BORDE,
      borderRadius: 6,
      borderWidth: 1,
      marginTop: 6,
      padding: 10,
    },
    noteTitle: {
      color: colorMarca,
      fontFamily: 'Helvetica-Bold',
      fontSize: 8,
      marginBottom: 3,
      textTransform: 'uppercase',
    },
    noteText: {
      color: COLOR_SECUNDARIO,
      fontSize: 8,
    },
    footerRule: {
      backgroundColor: COLOR_BORDE,
      bottom: 34,
      height: 1,
      left: 38,
      position: 'absolute',
      right: 38,
    },
    footerDisclaimer: {
      bottom: 20,
      color: COLOR_SECUNDARIO,
      fontSize: 6.5,
      left: 38,
      position: 'absolute',
      width: 390,
    },
    pageNumber: {
      bottom: 20,
      color: COLOR_SECUNDARIO,
      fontFamily: 'Helvetica-Bold',
      fontSize: 6.5,
      left: 457,
      position: 'absolute',
      textAlign: 'right',
      width: 100,
    },
  });
}

export type MealPlanPdfStyles = ReturnType<typeof crearEstilosPdf>;
